apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongo-ent.fullname" . }}
  labels:
    app: {{ include "mongo-ent.name" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "mongo-ent.name" . }}
  ports:
  - port: 27017
    targetPort: 27017
