storage:
  dbPath: /data/db
net:
  bindIp: 0.0.0.0
  port: 27017
  tls:
    mode: requireTLS
    certificateKeyFile: /var/lib/mongo/certs/server_mongo.pem
    CAFile: /var/lib/mongo/certs/ca.crt
    allowConnectionsWithoutCertificates: false
security:
  authorization: enabled
  keyFile: /etc/secrets/keyfile
replication:
  replSetName: rs0
